# Generated by Django 3.0.6 on 2020-05-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('adinfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adinfo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qnai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('typeofop', models.CharField(choices=[('st', 'startup'), ('sh', 'shutdown'), ('ma', 'maintenance')], default='st', max_length=2, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questioni', to='industry.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Qnae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('typeofop', models.CharField(choices=[('st', 'startup'), ('sh', 'shutdown'), ('ma', 'maintenance')], default='st', max_length=2, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questione', to='industry.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='industry',
            field=models.ManyToManyField(related_name='equipment', to='industry.Industry'),
        ),
    ]
