# Generated by Django 3.0.6 on 2020-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
