# Generated by Django 3.0.6 on 2020-07-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_industry_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnae',
            name='typeofop',
        ),
        migrations.RemoveField(
            model_name='qnai',
            name='typeofop',
        ),
    ]
