# Generated by Django 3.0.6 on 2020-07-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0003_auto_20200704_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnae',
            name='typeofop',
            field=models.CharField(choices=[('st', 'startup'), ('sh', 'shutdown'), ('ma', 'maintenance')], default='st', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='qnai',
            name='typeofop',
            field=models.CharField(choices=[('st', 'startup'), ('sh', 'shutdown'), ('ma', 'maintenance')], default='st', max_length=2, null=True),
        ),
    ]
