# Generated by Django 3.0.6 on 2020-07-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_auto_20200704_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnae',
            name='typeofop',
        ),
        migrations.RemoveField(
            model_name='qnai',
            name='typeofop',
        ),
    ]
