# Generated by Django 3.0.6 on 2020-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_auto_20200704_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
