# Generated by Django 3.0.6 on 2020-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_equipment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='trending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
