# Generated by Django 3.0.6 on 2020-07-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0009_equipment_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
