# Generated by Django 3.0.6 on 2020-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0010_industry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
