# Generated by Django 3.0.6 on 2020-07-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0012_auto_20200711_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
