# Generated by Django 3.0.6 on 2020-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0013_auto_20200711_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='seemore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
