# Generated by Django 3.0.6 on 2020-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0014_industry_seemore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carddetail', models.CharField(max_length=200)),
                ('adinfo', models.TextField(blank=True, null=True)),
                ('trending', models.BooleanField(default=False, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
